# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/agc.xdc

# Block Designs: bd/styx_ps/styx_ps.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==styx_ps || ORIG_REF_NAME==styx_ps} -quiet] -quiet

# IP: bd/styx_ps/ip/styx_ps_processing_system7_0_0/styx_ps_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==styx_ps_processing_system7_0_0 || ORIG_REF_NAME==styx_ps_processing_system7_0_0} -quiet] -quiet

# XDC: bd/styx_ps/styx_ps_ooc.xdc
