# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/rzinkstok/fpga_agc/agc.srcs/sources_1/ip/cmd_fifo/cmd_fifo.xci
# IP: The module: 'cmd_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rzinkstok/fpga_agc/agc.srcs/sources_1/ip/cmd_fifo/cmd_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'cmd_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/rzinkstok/fpga_agc/agc.srcs/sources_1/ip/cmd_fifo/cmd_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'cmd_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/rzinkstok/fpga_agc/agc.srcs/sources_1/ip/cmd_fifo/cmd_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cmd_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/rzinkstok/fpga_agc/agc.srcs/sources_1/ip/cmd_fifo/cmd_fifo.xci
# IP: The module: 'cmd_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rzinkstok/fpga_agc/agc.srcs/sources_1/ip/cmd_fifo/cmd_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'cmd_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/rzinkstok/fpga_agc/agc.srcs/sources_1/ip/cmd_fifo/cmd_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'cmd_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/rzinkstok/fpga_agc/agc.srcs/sources_1/ip/cmd_fifo/cmd_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cmd_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
