# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/rzinkstok/fpga_agc/agc.srcs/sources_1/ip/prop_clock_divider/prop_clock_divider.xci
# IP: The module: 'prop_clock_divider' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rzinkstok/fpga_agc/agc.srcs/sources_1/ip/prop_clock_divider/prop_clock_divider_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'prop_clock_divider'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/rzinkstok/fpga_agc/agc.srcs/sources_1/ip/prop_clock_divider/prop_clock_divider.xdc
# XDC: The top module name and the constraint reference have the same name: 'prop_clock_divider'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/rzinkstok/fpga_agc/agc.srcs/sources_1/ip/prop_clock_divider/prop_clock_divider_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prop_clock_divider'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/rzinkstok/fpga_agc/agc.srcs/sources_1/ip/prop_clock_divider/prop_clock_divider.xci
# IP: The module: 'prop_clock_divider' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rzinkstok/fpga_agc/agc.srcs/sources_1/ip/prop_clock_divider/prop_clock_divider_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'prop_clock_divider'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/rzinkstok/fpga_agc/agc.srcs/sources_1/ip/prop_clock_divider/prop_clock_divider.xdc
# XDC: The top module name and the constraint reference have the same name: 'prop_clock_divider'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/rzinkstok/fpga_agc/agc.srcs/sources_1/ip/prop_clock_divider/prop_clock_divider_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prop_clock_divider'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
