# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/rzinkstok/fpga_agc/fpga/agc.srcs/sources_1/ip/rope_memory/rope_memory.xci
# IP: The module: 'rope_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rzinkstok/fpga_agc/fpga/agc.srcs/sources_1/ip/rope_memory/rope_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rope_memory'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/rzinkstok/fpga_agc/fpga/agc.srcs/sources_1/ip/rope_memory/rope_memory.xci
# IP: The module: 'rope_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rzinkstok/fpga_agc/fpga/agc.srcs/sources_1/ip/rope_memory/rope_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rope_memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
